### ISSUE TITLE
Build a Cloudflare Pages Web App to Display News

### ISSUE THREAD

**Issue by v4ex-inc** [v4ex/com.v4ex.News#1]
# Tasks
* [ ] 1. Use [React.js](https://github.com/v4ex/WORKLOGS/wiki/React.js) as primary web app framework to build a native Cloudflare Pages Web App, decide tech stack.
* [ ] 2. Build Version 0.1.0:
* [ ]   - 2.1. Simple layout: Header, Main.
* [ ]   - 2.2. Required components: Brand Logo, Menu, List of Articles, Article Item.
* [ ]   - 2.3. Tests
* [ ] 3. Build Version 0.2.0:
* [ ]   - 3.1. Author Card
* [ ]   - 3.2. Author Page
* [ ]   - 3.3. Tests 

## 1. Use React.js, Choose Tech Stack
1. https://reactfordesigners.com
2. https://github.com/ustwo/ustwo.com-frontend
2.1. https://github.com/ustwo/ustwo.com-frontend/tree/master/src/app/components

----------------------------------------

## 2. V4EX News Version 0.1.0

----------------------------------------
